language: objective-c
osx_image: xcode7.3
install:
  - carthage bootstrap --no-use-binaries
  - git clone https://github.com/facebook/xctool.git
script:
  - xctool/xctool.sh -project "Alexander.xcodeproj" -scheme "Alexander-iOS" -sdk "iphonesimulator" build test
  - xctool/xctool.sh -project "Alexander.xcodeproj" -scheme "Alexander-macOS" -sdk "macosx" build test
  - pod spec lint
