language: objective-c
osx_image: xcode7.2
xcode_project: Alexander.xcodeproj
install:
  - carthage bootstrap
script:
  - xctool -project "Alexander.xcodeproj" -scheme "Alexander iOS" -sdk "iphonesimulator" build test
  - xctool -project "Alexander.xcodeproj" -scheme "Alexander macOS" -sdk "macosx" build test
  - pod lib lint
